// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./components/article-card.vue')['default']
    BlogSection: typeof import('./components/blog-section.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    CategoryPreview: typeof import('./components/category-preview.vue')['default']
    Collection: typeof import('./components/collection.vue')['default']
    CTA01: typeof import('./components/CTA01.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FooterHeading: typeof import('./components/FooterHeading.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Loading: typeof import('./components/loading.vue')['default']
    MinusSmIcon: typeof import('~icons/mi/nus-sm-icon')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PerkHeadings: typeof import('./components/PerkHeadings.vue')['default']
    ProductCard: typeof import('./components/product-card.vue')['default']
    ProjectCard: typeof import('./components/project-card.vue')['default']
    README: typeof import('./components/README.md')['default']
    StatisticSection: typeof import('./components/statistic-section.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
    TrendingHeading: typeof import('./components/TrendingHeading.vue')['default']
  }
}

export { }
